const todoList=document.querySelector(".todo-list")
todoList.insertAdjacentHTML("beforeend","<li>TEACHING</li>")
// todoList.insertAdjacentHTML("afterbegin","<li>TEACHING</li>")
// todoList.insertAdjacentHTML("beforeend","<li>TEACHING</li>")
// todoList.insertAdjacentHTML("afterend","<li>TEACHING</li>")